name: cavOS ISO Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: sudo apt install -y nasm build-essential binutils grub-common xorriso mtools make
      
    - name: Compile kernel
      run: make build
      
    - name: Clean temporary bins
      run: make clear
      
    - name: Commit files
      run: |
        git config --local user.name "malwarepad"
        git add ./cavOS.iso
        git commit -m "`date +"%T"`> Auto update"
    - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
