name: cavOS ISO Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: sudo apt install -y nasm build-essential binutils grub-common xorriso mtools make
      
    - name: Compile kernel
      run: make build
      
    - name: Clean temporary bins
      run: make clear
